export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST";
export const ADD_CATEGORY_REQUEST_SUCCESS = "ADD_CATEGORY_REQUEST_SUCCESS";
export const ADD_CATEGORY_REQUEST_FAILURE = "ADD_CATEGORY_REQUEST_FAILURE";

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST";
export const GET_CATEGORY_REQUEST_SUCCESS = "GET_CATEGORY_REQUEST_SUCCESS";
export const GET_CATEGORY_REQUEST_FAILURE = "GET_CATEGORY_REQUEST_FAILURE";

export const GET_CATEGORY_BY_ID_REQUEST = "GET_CATEGORY_BY_ID_REQUEST";
export const GET_CATEGORY_BY_ID_REQUEST_SUCCESS =
  "GET_CATEGORY_BY_ID_REQUEST_SUCCESS";
export const GET_CATEGORY_BY_ID_REQUEST_FAILURE =
  "GET_CATEGORY_BY_ID_REQUEST_FAILURE";
