export const SET_EMPLOYEE_DATA = "SET_EMPLOYEE_DATA";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SET_TOTAL_EMPLOYEES_COUNT = "SET_TOTAL_EMPLOYEES_COUNT";
