export const SET_EMPLOYEE_DATA = "SET_EMPLOYEE_DATA";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const SET_TOTAL_EMPLOYEES_COUNT = "SET_TOTAL_EMPLOYEES_COUNT";

export const GET_EMPLOYEE_BY_ID_REQUEST = "GET_EMPLOYEE_BY_ID_REQUEST";
export const GET_EMPLOYEE_BY_ID_REQUEST_SUCCESS =
  "GET_EMPLOYEE_BY_ID_REQUEST_SUCCESS";
export const GET_EMPLOYEE_BY_ID_REQUEST_FAILURE =
  "GET_EMPLOYEE_BY_ID_REQUEST_FAILURE";

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_REQUEST_SUCCESS =
  "UPDATE_EMPLOYEE_REQUEST_SUCCESS";
export const UPDATE_EMPLOYEE_REQUEST_FAILURE =
  "UPDATE_EMPLOYEE_REQUEST_FAILURE";
