export const GET_EMPLOYEE_BY_ID_REQUEST = "GET_EMPLOYEE_BY_ID_REQUEST";
export const GET_EMPLOYEE_BY_ID_REQUEST_SUCCESS =
  "GET_EMPLOYEE_BY_ID_REQUEST_SUCCESS";
export const GET_EMPLOYEE_BY_ID_REQUEST_FAILURE =
  "GET_EMPLOYEE_BY_ID_REQUEST_FAILURE";

export const UPDATE_EMPLOYEE_REQUEST = "UPDATE_EMPLOYEE_REQUEST";
export const UPDATE_EMPLOYEE_REQUEST_SUCCESS =
  "UPDATE_EMPLOYEE_REQUEST_SUCCESS";
export const UPDATE_EMPLOYEE_REQUEST_FAILURE =
  "UPDATE_EMPLOYEE_REQUEST_FAILURE";

export const GET_EMPLOYEE_REQUEST = "GET_EMPLOYEE_REQUEST";
export const GET_EMPLOYEE_REQUEST_SUCCESS = "GET_EMPLOYEE_REQUEST_SUCCESS";
export const GET_EMPLOYEE_REQUEST_FAILURE = "GET_EMPLOYEE_REQUEST_FAILURE";

export const ADD_EMPLOYEE_REQUEST = "ADD_EMPLOYEE_REQUEST";
export const ADD_EMPLOYEE_REQUEST_SUCCESS = "ADD_EMPLOYEE_REQUEST_SUCCESS";
export const ADD_EMPLOYEE_REQUEST_FAILURE = "ADD_EMPLOYEE_REQUEST_FAILURE";

export const DELETE_EMPLOYEE_REQUEST = "DELETE_EMPLOYEE_REQUEST";
export const DELETE_EMPLOYEE_REQUEST_SUCCESS =
  "DELETE_EMPLOYEE_REQUEST_SUCCESS";
export const DELETE_EMPLOYEE_REQUEST_FAILURE =
  "DELETE_EMPLOYEE_REQUEST_FAILURE";

export const TOTAL_EMPLOYEE_COUNT_REQUEST = "TOTAL_EMPLOYEE_COUNT_REQUEST";
export const TOTAL_EMPLOYEE_COUNT_REQUEST_SUCCESS =
  "TOTAL_EMPLOYEE_COUNT_REQUEST_SUCCESS";
export const TOTAL_EMPLOYEE_COUNT_REQUEST_FAILURE =
  "TOTAL_EMPLOYEE_COUNT_REQUEST_FAILURE";
