// post
// add new order
export const ADD_ORDER_REQUEST = "ADD_ORDER_REQUEST";
export const ADD_ORDER_REQUEST_SUCCESS = "ADD_ORDER_REQUEST_SUCCESS";
export const ADD_ORDER_REQUEST_FAILURE = "ADD_ORDER_REQUEST_FAILURE";

// get
// get all order
export const GET_ORDERS_REQUEST = "GET_ORDERS_REQUEST";
export const GET_ORDERS_REQUEST_SUCCESS = "GET_ORDERS_REQUEST_SUCCESS";
export const GET_ORDERS_REQUEST_FAILURE = "GET_ORDERS_REQUEST_FAILURE";
// get single order by id
export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST";
export const GET_ORDER_BY_ID_REQUEST_SUCCESS =
  "GET_ORDER_BY_ID_REQUEST_SUCCESS";
export const GET_ORDER_BY_ID_REQUEST_FAILURE =
  "GET_ORDER_BY_ID_REQUEST_FAILURE";

// delete
// delete single order by id
export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_REQUEST_SUCCESS = "DELETE_ORDER_REQUEST_SUCCESS";
export const DELETE_ORDER_REQUEST_FAILURE = "DELETE_ORDER_REQUEST_FAILURE";

// update
// update single order
export const UPDATE_ORDER_REQUEST = "UPDATE_ORDER_REQUEST";
export const UPDATE_ORDER_REQUEST_SUCCESS = "UPDATE_ORDER_REQUEST_SUCCESS";
export const UPDATE_ORDER_REQUEST_FAILURE = "UPDATE_ORDER_REQUEST_FAILURE";
// update single order's item's status
export const UPDATE_ORDER_ITEM_STATUS_REQUEST =
  "UPDATE_ORDER_ITEM_STATUS_REQUEST";
export const UPDATE_ORDER_ITEM_STATUS_REQUEST_SUCCESS =
  "UPDATE_ORDER_ITEM_STATUS_REQUEST_SUCCESS";
export const UPDATE_ORDER_ITEM_STATUS_REQUEST_FAILURE =
  "UPDATE_ORDER_ITEM_STATUS_REQUEST_FAILURE";
// update single order's status
export const UPDATE_ORDER_STATUS_REQUEST = "UPDATE_ORDER_STATUS_REQUEST";
export const UPDATE_ORDER_STATUS_REQUEST_SUCCESS =
  "UPDATE_ORDER_STATUS_REQUEST_SUCCESS";
export const UPDATE_ORDER_STATUS_REQUEST_FAILURE =
  "UPDATE_ORDER_STATUS_REQUEST_FAILURE";

// count
// count totals
export const TOTAL_ORDERS_COUNT_REQUEST = "TOTAL_ORDERS_COUNT_REQUEST";
export const TOTAL_ORDERS_COUNT_REQUEST_SUCCESS =
  "TOTAL_ORDERS_COUNT_REQUEST_SUCCESS";
export const TOTAL_ORDERS_COUNT_REQUEST_FAILURE =
  "TOTAL_ORDERS_COUNT_REQUEST_FAILURE";
