export const SET_PRODUCT_DATA = "SET_PRODUCT_DATA";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SET_TOTAL_PRODUCTS_COUNT = "SET_TOTAL_PRODUCTS_COUNT";
export const SET_FILTERED_PRODUCT_DATA = "SET_FILTERED_PRODUCT_DATA";

export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_REQUEST_SUCCESS =
  "GET_PRODUCT_BY_ID_REQUEST_SUCCESS";
export const GET_PRODUCT_BY_ID_REQUEST_FAILURE =
  "GET_PRODUCT_BY_ID_REQUEST_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_REQUEST_SUCCESS = "UPDATE_PRODUCT_REQUEST_SUCCESS";
export const UPDATE_PRODUCT_REQUEST_FAILURE = "UPDATE_PRODUCT_REQUEST_FAILURE";
