export const GET_PRODUCT_BY_ID_REQUEST = "GET_PRODUCT_BY_ID_REQUEST";
export const GET_PRODUCT_BY_ID_REQUEST_SUCCESS =
  "GET_PRODUCT_BY_ID_REQUEST_SUCCESS";
export const GET_PRODUCT_BY_ID_REQUEST_FAILURE =
  "GET_PRODUCT_BY_ID_REQUEST_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_REQUEST_SUCCESS = "UPDATE_PRODUCT_REQUEST_SUCCESS";
export const UPDATE_PRODUCT_REQUEST_FAILURE = "UPDATE_PRODUCT_REQUEST_FAILURE";

export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_REQUEST_SUCCESS = "GET_PRODUCT_REQUEST_SUCCESS";
export const GET_PRODUCT_REQUEST_FAILURE = "GET_PRODUCT_REQUEST_FAILURE";

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
export const ADD_PRODUCT_REQUEST_SUCCESS = "ADD_PRODUCT_REQUEST_SUCCESS";
export const ADD_PRODUCT_REQUEST_FAILURE = "ADD_PRODUCT_REQUEST_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_REQUEST_SUCCESS = "DELETE_PRODUCT_REQUEST_SUCCESS";
export const DELETE_PRODUCT_REQUEST_FAILURE = "DELETE_PRODUCT_REQUEST_FAILURE";

export const TOTAL_PRODUCT_COUNT_REQUEST = "TOTAL_PRODUCT_COUNT_REQUEST";
export const TOTAL_PRODUCT_COUNT_REQUEST_SUCCESS =
  "TOTAL_PRODUCT_COUNT_REQUEST_SUCCESS";
export const TOTAL_PRODUCT_COUNT_REQUEST_FAILURE =
  "TOTAL_PRODUCT_COUNT_REQUEST_FAILURE";

export const GET_FILTERED_PREODUCT_REQUEST =
  "GET_FILTERED_PREODUCT_DATA_REQUEST";
export const GET_FILTERED_PREODUCT_REQUEST_SUCCESS =
  "GET_FILTERED_PREODUCT_REQUEST_SUCCESS";
export const GET_FILTERED_PREODUCT_REQUEST_FAILURE =
  "GET_FILTERED_PREODUCT_DATA_REQUEST_FAILURE";
