export const SET_TABLE_DATA = "SET_TABLE_DATA";
export const SET_RESERVED_TABLES = "SET_RESERVED_TABLES";
export const MADE_TABLE_RESERVED = "MADE_TABLE_RESERVED";
export const MADE_TABLE_AVAILABLE = "MADE_TABLE_AVAILABLE";
export const ADD_TABLE_REQUEST_SUCCESS = "ADD_TABLE_REQUEST_SUCCESS";
