export const SET_TABLE_DATA = "SET_TABLE_DATA";
export const SET_RESERVED_TABLES = "SET_RESERVED_TABLES";
export const MADE_TABLE_RESERVED = "MADE_TABLE_RESERVED";
export const MADE_TABLE_AVAILABLE = "MADE_TABLE_AVAILABLE";
export const ADD_TABLE_REQUEST_SUCCESS = "ADD_TABLE_REQUEST_SUCCESS";

export const DELETE_TABLE_REQUEST = "DELETE_TABLE_REQUEST";
export const DELETE_TABLE_REQUEST_SUCCESS = "DELETE_TABLE_REQUEST_SUCCESS";
export const DELETE_TABLE_REQUEST_FAILURE = "DELETE_TABLE_REQUEST_FAILURE";

export const UPDATE_TABLE_REQUEST = "UPDATE_TABLE_REQUEST";
export const UPDATE_TABLE_REQUEST_SUCCESS = "UPDATE_TABLE_REQUEST_SUCCESS";
export const UPDATE_TABLE_REQUEST_FAILURE = "UPDATE_TABLE_REQUEST_FAILURE";

export const GET_TABLE_BY_ID_REQUEST = "GET_TABLE_BY_ID_REQUEST";
export const GET_TABLE_BY_ID_REQUEST_SUCCESS =
  "GET_TABLE_BY_ID_REQUEST_SUCCESS";
export const GET_TABLE_BY_ID_REQUEST_FAILURE =
  "GET_TABLE_BY_ID_REQUEST_FAILURE";
